### ISSUE TITLE
ProductDistributions

### ISSUE THREAD

**Issue by atteson** [gragusa/BayesianTools.jl#6]
I suggest you add ProductDistributions to Distributions and do a pull request.  It seems useful enough to be included.

Otherwise, are you planning on registering this package?

**Comment by gragusa** [comment]
Probably better to register, but I would like to wait for 0.7.

Do you have suggestions on things that could be included in the package?

**Comment by atteson** [comment]
I've been using it a bit and, so far, have found the following useful:

```julia
# this is needed for the MultivariateDistribution interface described here:
# https://juliastats.github.io/Distributions.jl/latest/extends.html#Create-a-Multivariate-Distribution-1
Distributions._rand!( d::ProductDistribution, a::AbstractArray ) = rand!( d, a )

Distributions.params( d::ProductDistribution ) = union(params.(d.marginals))
```

**Comment by gragusa** [comment]
Would you be willing to do  a PR to add these two methods?

**Comment by gragusa** [comment]
Closing as the package is now registered.
